# ┌1────────────────────┐
# │ Pixel 8 = shiba     │
# │ Pixel 8 Pro = husky │
    DEVICE_CODENAME=shiba
# └─────────────────────┘

# ┌2───────────────────────────────────────────────────────────────────────────────────────────┐
# │ Заполняется по AVB-метаданным оригинального boot.img.                                      │
# │ Их получаем при помощи avbtool.py:                                                         │
# │ https://android.googlesource.com/platform/external/avb/+/refs/heads/main-kernel/avbtool.py │
# │ python3 ./avbtool.py info_image --image [оригинальный boot.img]                            │
# │ Заполняем конфиг ниже исходя из вывода в консоли.                                          │
# │ Заполняйте поля с соответствующим префиксом, исходя от типа прошивки.                      │
    STABLE_rollback_index=1780617600
    STABLE_salt=6caae4112961def27eeacd6573fb2417a926db7e6619a8aec1f8c3cf70a70ade
    STABLE_os_version=17
    STABLE_fingerprint=google/${DEVICE_CODENAME}/${DEVICE_CODENAME}:17/CP2A.260605.012/15430684:user/release-keys
    STABLE_security_patch=2026-06-05

    BETA_rollback_index=1777939200
    BETA_salt=6caae4112961def27eeacd6573fb2417a926db7e6619a8aec1f8c3cf70a70ade
    BETA_os_version=17
    BETA_fingerprint=google/${DEVICE_CODENAME}_beta/${DEVICE_CODENAME}:17/CP21.260330.011/15499021:user/release-keys
    BETA_security_patch=2026-05-05
# └────────────────────────────────────────────────────────────────────────────────────────────┘

# ┌3─────────────────────────────────────────────────────────────┐
# │ МЕНЯТЬ ТОЛЬКО В СЛУЧАЕ                                       │
# │ ОБНОВЛЕНИЯ ПАТЧЕЙ В ПАПКЕ patches                            │
# │ Патчи взяты с: https://github.com/WildKernels/kernel_patches │
    KSU_NEXT_COMMIT="HEAD"
    SUSFS_COMMIT="4a1e8311ae24bffb82c97b15945a7d94bf04cf90"

    KSU_COMMIT="fda952bffe54c52d63f210358d47610cd9175cea"
    SUSFS_KSU_COMMIT="efac30349e0660577f753b1fbaad43f0407d05d0"

    KSU_NEXT_PATCHES=(
        "ksun-5a4a718-susfs-f7ae19ef-gki-android14-6.1.patch"
    )

    KERNELSOURCE_PATCHES=(
        "fix_namespace.c.patch"
    )
# └──────────────────────────────────────────────────────────────┘


# ┌4─────────────────────────────────────────────────────────────────┐
# │ Определяет ветку клонируемую с:                                  │
# │ https://android.googlesource.com/kernel/common/+refs             │
# │ В makefile каждой ветки, который находится в корне репозитория,  │
# │ всегда указана нумерация ядра.                                   │
# │ Выбирается в соответствии с версией ядра установленной прошивки. │
    STABLE_BRANCH="android14-6.1-2025-12"
    BETA_BRANCH="android14-6.1-2025-12"
# └──────────────────────────────────────────────────────────────────┘

# ┌5─────────────────────────────────────────────┐
# │ Содержит драйвера, инструменты сборки и т.д. │
# │ Ссылка на репозиторий:                       │
# │ https://gitlab.com/grapheneos/kernel_pixel   │
    PIXEL_TAG="2026061600"
    PIXEL_COMMIT="cb8a117068b02906eaa940c38a10fd23bc3a8efa"
# └──────────────────────────────────────────────┘
