name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      firmware:
        type: choice
        description: "Firmware type"
        options:
          - stable
          - beta
      ksu_type:
        type: choice
        description: "KernelSU type"
        options:
          - ksu
          - ksun
          - sukisu

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: false
          haskell: false
          large-packages: false
          docker-images: false
          swap-storage: true
        
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full zip git curl wget

      - name: First Install
        run: ./first_install.sh

      - name: Build Kernel
        run: ./build_ksu.sh --${{ inputs.firmware }} --${{ inputs.ksu_type }}
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: boot_${{ inputs.firmware }}_${{ inputs.ksu_type }}
          path: output/*
          retention-days: 1
          archive: true
